/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.verisec.realestateeth.forms;

import com.verisec.realestateeth.controller.ContractsController;
import com.verisec.realestateeth.domain.beans.Offer;
import com.verisec.realestateeth.domain.beans.User;
import com.verisec.realestateeth.table.model.OfferTableModel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Natasa Vatres
 */
public class FAcceptOffer extends javax.swing.JFrame {

    /**
     * Creates new form FAcceptOffer
     */
    public FAcceptOffer() {
        initComponents();
    }

    User currentUser;
    ContractsController contractsController = new ContractsController();

    final static Logger LOGGER = Logger.getLogger(FAcceptOffer.class);

    FAcceptOffer(User seller) {
        initComponents();
        currentUser = seller;
        centerForm();
        setStatusBar();
        populateTableOffers(seller);
        setColumnSizes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblOffers = new javax.swing.JTable();
        jBttnAccept = new javax.swing.JButton();
        jBttnDecline = new javax.swing.JButton();
        jBttnBack = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Received offers");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Current offers ");

        jTblOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblOffers);

        jBttnAccept.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBttnAccept.setText("Accept");
        jBttnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAcceptActionPerformed(evt);
            }
        });

        jBttnDecline.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBttnDecline.setText("Decline");
        jBttnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnDeclineActionPerformed(evt);
            }
        });

        jBttnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBttnBack.setText("Back");
        jBttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBttnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBttnDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnAccept)
                    .addComponent(jBttnDecline))
                .addGap(18, 18, 18)
                .addComponent(jBttnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List<Offer> offers;
    Offer currentOffer;
    String contractAddress;

    private void jBttnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAcceptActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTblOffers.getSelectedRow();

        OfferTableModel offerTableModel = (OfferTableModel) jTblOffers.getModel();

        if (selectedRow >= 0) {

            try {
                currentOffer = offers.get(selectedRow);
                contractAddress = currentOffer.getContractAddress();
                contractsController.acceptOffer(contractAddress, currentUser, offers, currentOffer);

                JOptionPane.showMessageDialog(null, "Offer accepted!");
                offers.remove(selectedRow);

                offerTableModel.refreshTable();

            } catch (Exception ex) {
                LOGGER.error("Error in accepting offer", ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select offer!");
        }
    }//GEN-LAST:event_jBttnAcceptActionPerformed

    private void jBttnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnDeclineActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTblOffers.getSelectedRow();

        OfferTableModel offerTableModel = (OfferTableModel) jTblOffers.getModel();

        if (selectedRow >= 0) {
            try {
                contractAddress = offers.get(selectedRow).getContractAddress();
                contractsController.declineOffer(contractAddress, currentUser);

                JOptionPane.showMessageDialog(null, "Offer declined!");
                offers.remove(selectedRow);

                offerTableModel.refreshTable();

            } catch (Exception ex) {
                LOGGER.error("Error in declining offer", ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select offer!");
        }
    }//GEN-LAST:event_jBttnDeclineActionPerformed

    private void jBttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBttnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAccept;
    private javax.swing.JButton jBttnBack;
    private javax.swing.JButton jBttnDecline;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblOffers;
    // End of variables declaration//GEN-END:variables

    private void populateTableOffers(User seller) {
        try {
            offers = contractsController.getOffersSeller(seller);
            TableModel tm = new OfferTableModel(offers);
            jTblOffers.setModel(tm);
        } catch (Exception ex) {
            LOGGER.error("Error in populating table with real estates", ex);
        }
    }

    private void centerForm() {
        setLocationRelativeTo(null);
    }

    private void setColumnSizes() {
        jTblOffers.setRowHeight(20);

        TableColumnModel columnModel = jTblOffers.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(300);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(100);
    }

    JPanel statusPanel;
    JLabel statusLabel;

    private void setStatusBar() {
        setLayout(new BorderLayout());

        statusPanel = new JPanel();
        add(statusPanel, BorderLayout.SOUTH);

        statusPanel.setPreferredSize(new Dimension(getWidth(), 30));
        statusPanel.setLayout(new BoxLayout(statusPanel, BoxLayout.X_AXIS));
        statusLabel = new JLabel("  User:   " + currentUser);
        statusLabel.setHorizontalAlignment(SwingConstants.LEFT);
        statusPanel.add(statusLabel);
    }
}
