/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.verisec.realestateeth.forms;

import com.verisec.realestateeth.controller.Controller;
import com.verisec.realestateeth.domain.Offer;
import com.verisec.realestateeth.domain.RealEstate;
import com.verisec.realestateeth.domain.User;
import com.verisec.realestateeth.table.model.OfferTableModel;
import com.verisec.realestateeth.table.model.RealEstateTableModel;
import java.math.BigInteger;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Natasa Vatres
 */
public class FAcceptOffer extends javax.swing.JFrame {

    /**
     * Creates new form FAcceptOffer
     */
    public FAcceptOffer() {
        initComponents();
    }

    User currentUser;
    Controller controller = new Controller();

    FAcceptOffer(User seller) {
        initComponents();
        currentUser = seller;
        centerForm();
        populateTableOffers(seller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblOffers = new javax.swing.JTable();
        jBttnAccept = new javax.swing.JButton();
        jBttnDecline = new javax.swing.JButton();
        jBttnBack = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Received offers");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Current offers ");

        jTblOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblOffers);

        jBttnAccept.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBttnAccept.setText("Accept");
        jBttnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAcceptActionPerformed(evt);
            }
        });

        jBttnDecline.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBttnDecline.setText("Decline");
        jBttnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnDeclineActionPerformed(evt);
            }
        });

        jBttnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBttnBack.setText("Back");
        jBttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBttnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBttnDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnAccept)
                    .addComponent(jBttnDecline))
                .addGap(18, 18, 18)
                .addComponent(jBttnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List<Offer> offers;
    String contractAddress;

    private void jBttnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAcceptActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTblOffers.getSelectedRow();

        OfferTableModel offerTableModel = (OfferTableModel) jTblOffers.getModel();
        
        if (selectedRow >= 0) {

            try {
                contractAddress = offers.get(selectedRow).getContractAddress();
                controller.acceptOffer(contractAddress, currentUser);

                JOptionPane.showMessageDialog(null, "Offer accepted!");
                offers.remove(selectedRow);

                offerTableModel.refreshTable();

            } catch (Exception ex) {
                System.out.println("Error in accepting offer");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select offer!");
        }
    }//GEN-LAST:event_jBttnAcceptActionPerformed

    private void jBttnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnDeclineActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTblOffers.getSelectedRow();

        OfferTableModel offerTableModel = (OfferTableModel) jTblOffers.getModel();

        if (selectedRow >= 0) {
            try {
                contractAddress = offers.get(selectedRow).getContractAddress();
                controller.declineOffer(contractAddress, currentUser);

                JOptionPane.showMessageDialog(null, "Offer declined!");
                offers.remove(selectedRow);

                offerTableModel.refreshTable();

            } catch (Exception ex) {
                System.out.println("Error in declining offer");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select offer!");
        }
    }//GEN-LAST:event_jBttnDeclineActionPerformed

    private void jBttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBttnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAccept;
    private javax.swing.JButton jBttnBack;
    private javax.swing.JButton jBttnDecline;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblOffers;
    // End of variables declaration//GEN-END:variables

    private void populateTableOffers(User seller) {
        try {
            offers = controller.getOffersSeller(seller);
            TableModel tm = new OfferTableModel(offers);
            jTblOffers.setModel(tm);
        } catch (Exception ex) {
            System.out.println("Error in populating table with real estates");
        }
    }

    private void centerForm() {
        setLocationRelativeTo(null);
    }
}
